version: "3.8"
services:

    db:
        image: mariadb
        container_name: db_docker_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mariadb
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    php:
        build: php
        container_name: php_docker_symfony
        ports:
          - "8084:80"
        volumes:
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: